app_admin_weapon_creation:
    prefix: /creation/
    resource: "creation.yml"

app_admin_weapon_deletion:
    prefix: /deletion/
    resource: "deletion.yml"

app_admin_weapon_edition:
    prefix: /edition/
    resource: "edition.yml"

app_admin_weapon_listing:
    prefix: /listing/
    resource: "listing.yml"

app_admin_weapon_showing:
    prefix: /showing/
    resource: "showing.yml"

