app_admin_status_listing_list_status:
    path: /list_status/
    defaults: { _controller: 'AppBundle:Admin/Status/Listing:listStatus' }
    options:
        navbar:
        - icon: fa fa-plus
          text: Ajouter un statut
          route: app_admin_status_creation_create_status
