app_admin_posture_creation:
    prefix: /creation/
    resource: "creation.yml"

app_admin_posture_deletion:
    prefix: /deletion/
    resource: "deletion.yml"

app_admin_posture_edition:
    prefix: /edition/
    resource: "edition.yml"

app_admin_posture_listing:
    prefix: /listing/
    resource: "listing.yml"

app_admin_posture_showing:
    prefix: /showing/
    resource: "showing.yml"

