app_admin_item_creation:
    prefix: /creation/
    resource: "creation.yml"

app_admin_item_deletion:
    prefix: /deletion/
    resource: "deletion.yml"

app_admin_item_edition:
    prefix: /edition/
    resource: "edition.yml"

app_admin_item_listing:
    prefix: /listing/
    resource: "listing.yml"

app_admin_item_showing:
    prefix: /showing/
    resource: "showing.yml"

