# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_email_provider:
            entity:
                class: 'AppBundle:User'
                property: email
        user_username_provider:
            entity:
                class: 'AppBundle:User'
                property: username
        user_provider:
            chain:
                providers:
                    - user_email_provider
                    - user_username_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user_provider
            logout_on_user_change: true
            anonymous: ~
            pattern: ^/
            form_login:
                provider: user_provider
                login_path: app_user_authentication_authenticate
                check_path: app_user_authentication_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: app_user_authentication_logout
                target: /
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path:   /
            user_checker: AppBundle\Security\UserChecker
