app_user_forgot_password_request_token:
    path:   /request_token/
    defaults: { _controller: 'AppBundle:User\ForgotPassword:requestToken' }

app_user_forgot_password_check_token:
    path:   /check_token/{id}/{token}
    defaults: { _controller: 'AppBundle:User\ForgotPassword:checkToken' }
    requirements:
        id: \d+