app_admin_personage_model_edition_edit_personage_model:
    path: /edit_personage_model/{id}
    defaults: { _controller: 'AppBundle:Admin/PersonageModel/Edition:editPersonageModel' }
    requirements:
        id: \d+
