app_player_creation:
    prefix: /creation/
    resource: "creation.yml"

app_player_deletion:
    prefix: /deletion/
    resource: "deletion.yml"

app_player_edition:
    prefix: /edition/
    resource: "edition.yml"

app_player_listing:
    prefix: /listing/
    resource: "listing.yml"

app_player_showing:
    prefix: /showing/
    resource: "showing.yml"

