app_admin_god_creation:
    prefix: /creation/
    resource: "creation.yml"

app_admin_god_deletion:
    prefix: /deletion/
    resource: "deletion.yml"

app_admin_god_edition:
    prefix: /edition/
    resource: "edition.yml"

app_admin_god_listing:
    prefix: /listing/
    resource: "listing.yml"

app_admin_god_showing:
    prefix: /showing/
    resource: "showing.yml"

