app_admin_god_edition_edit_god:
    path: /edit_god/{id}
    defaults: { _controller: 'AppBundle:Admin/God/Edition:editGod' }
    options:
        navbar:
        -   icon: fa fa-plus
            route: app_admin_personage_model_creation_create_personage_model
            text: Ajouter un dieu
    requirements:
        id: \d+
