app_admin_god:
    prefix: /god/
    resource: "god/all.yml"

app_admin_implant:
    prefix: /implant/
    resource: "implant/all.yml"

app_admin_weapon:
    prefix: /weapon/
    resource: "weapon/all.yml"

app_admin_item:
    prefix: /item/
    resource: "item/all.yml"

