app_admin_god:
    prefix: /god/
    resource: "god/all.yml"

app_admin_implant_model:
    prefix: /implant_model/
    resource: "implant_model/all.yml"

app_admin_weapon_model:
    prefix: /weapon_model/
    resource: "weapon_model/all.yml"

app_admin_item_model:
    prefix: /item_model/
    resource: "item_model/all.yml"

app_admin_status:
    prefix: /status/
    resource: "status/all.yml"

app_admin_origin:
    prefix: /origin/
    resource: "origin/all.yml"

app_admin_posture:
    prefix: /posture/
    resource: "posture/all.yml"

app_admin_rank:
    prefix: /rank/
    resource: "rank/all.yml"

app_admin_wound:
    prefix: /wound/
    resource: "wound/all.yml"

app_admin_player:
    prefix: /player/
    resource: "player/all.yml"

app_admin_personage_model:
    prefix: /personage_model/
    resource: "personage_model/all.yml"

