app_admin_rank_creation:
    prefix: /creation/
    resource: "creation.yml"

app_admin_rank_deletion:
    prefix: /deletion/
    resource: "deletion.yml"

app_admin_rank_edition:
    prefix: /edition/
    resource: "edition.yml"

app_admin_rank_listing:
    prefix: /listing/
    resource: "listing.yml"

app_admin_rank_showing:
    prefix: /showing/
    resource: "showing.yml"

app_admin_rank_duplication:
    prefix: /duplication/
    resource: "duplication.yml"

