AppBundle\Entity\File:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\FileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        path:
            type: string
            length: 255
        lastUpdate:
            type: datetime
    lifecycleCallbacks: {  }
