AppBundle\Entity\God:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GodRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 2048
    oneToOne:
        image:
            targetEntity: AppBundle\Entity\File
    lifecycleCallbacks: {  }