AppBundle\Entity\Implant:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ImplantRepository
    fields:
        status:
            type: integer
    manyToOne:
        model:
            targetEntity: AppBundle\Entity\ImplantModel
            cascade: [persist]
    lifecycleCallbacks: {  }
