AppBundle\Entity\InventoryItemModel:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InventoryItemModelRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        weapon_model: WeaponModel
        item_model: ItemModel
        implant_model: ImplantModel
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 2048
    oneToOne:
        image:
            targetEntity: AppBundle\Entity\File
            cascade: [persist, remove]
    lifecycleCallbacks: {  }
