AppBundle\Entity\InventorySettingsModel:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InventorySettingsModelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        itemNumber:
            type: integer
            nullable: true
        weaponNumber:
            type: integer
            nullable: true
        implantNumber:
            type: integer
            nullable: true
        size:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
