AppBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ItemRepository
    manyToOne:
        model:
            targetEntity: AppBundle\Entity\ItemModel
            cascade: [persist]
    lifecycleCallbacks: {  }
