AppBundle\Entity\Player:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PlayerRepository
    manyToOne:
        god:
            targetEntity: AppBundle\Entity\God
            cascade: [persist]
        user:
            targetEntity: AppBundle\Entity\User
            cascade: [persist]
            inversedBy: players
    lifecycleCallbacks: {  }
