AppBundle\Entity\Weapon:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\WeaponRepository
    fields:
        status:
            type: integer
    manyToOne:
        model:
            targetEntity: AppBundle\Entity\WeaponModel
            cascade: [persist]
    lifecycleCallbacks: {  }
