-   text: main_menu
    route: app_admin_home_index
    icon: fas fa-tachometer-alt
-   text: player
    route: app_admin_player_listing_list_player
    icon: fas fa-user-secret
-   text: rank
    route: app_admin_rank_listing_list_rank
    icon: fas fa-id-badge
-   text: god
    route: app_admin_god_listing_list_god
    icon: fab fa-superpowers
-   text: personage
    route: app_admin_personage_model_listing_list_personage_model
    icon: fas fa-users
-   text: weapons
    route: app_admin_weapon_model_listing_list_weapon_model
    icon: fas fa-screwdriver
-   text: implant
    route: app_admin_implant_model_listing_list_implant_model
    icon: fas fa-bolt
-   text: item
    route: app_admin_item_model_listing_list_item_model
    icon: fas fa-cubes