-   text: main_menu
    route: app_admin_home_index
    icon: ra ra-spades-card
-   text: player
    route: app_admin_player_listing_list_player
    icon: ra ra-player
-   text: rank
    route: app_admin_rank_listing_list_rank
    icon: ra ra-crown
-   text: god
    route: app_admin_god_listing_list_god
    icon: ra ra-alien-fire ra-lg
-   text: personage
    route: app_admin_personage_model_listing_list_personage_model
    icon: ra ra-muscle-up
-   text: weapons
    route: app_admin_weapon_model_listing_list_weapon_model
    icon: ra ra-axe
-   text: implant
    route: app_admin_implant_model_listing_list_implant_model
    icon: ra ra-regeneration
-   text: item
    route: app_admin_item_model_listing_list_item_model
    icon: ra ra-key
-   text: inventory
    route: app_admin_inventory_model_listing_list_inventory_model
    icon: ra ra-ammo-bag
-   text: origin
    route: app_admin_origin_listing_list_origin
    icon: fas fa-passport
-   text: wound
    route: app_admin_wound_listing_list_wound
    icon: ra ra-player-pain
-   text: status
    route: app_admin_status_listing_list_status
    icon: fas fa-info
-   text: posture
    route: app_admin_posture_listing_list_posture
    icon: ra ra-player-teleport