app_admin_item_model_creation:
    prefix: /creation/
    resource: "creation.yml"

app_admin_item_model_deletion:
    prefix: /deletion/
    resource: "deletion.yml"

app_admin_item_model_edition:
    prefix: /edition/
    resource: "edition.yml"

app_admin_item_model_listing:
    prefix: /listing/
    resource: "listing.yml"

app_admin_item_model_showing:
    prefix: /showing/
    resource: "showing.yml"

app_admin_item__model_duplication:
    prefix: /duplication/
    resource: "duplication.yml"

