app_admin_weapon_model_deletion_delete_weapon_model:
    path: /delete_weapon_model/{id}
    defaults: { _controller: 'AppBundle:Admin/WeaponModel/Deletion:deleteWeaponModel' }
    requirements:
        id: \d+
