app_admin_weapon_model_edition_edit_weapon_model:
    path: /edit_weapon_model/{id}
    defaults: { _controller: 'AppBundle:Admin/WeaponModel/Edition:editWeaponModel' }
    requirements:
        id: \d+
