app_admin_weapon_model_listing_list_weapon_model:
    path: /list_weapon_model/
    defaults: { _controller: 'AppBundle:Admin/WeaponModel/Listing:listWeaponModel' }
    options:
        navbar:
        - icon: fa fa-plus
          text: Ajouter une arme
          route: app_admin_weapon_model_creation_create_weapon_model